services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: fastapi run main.py --port 8000